### ISSUE TITLE
Черный экран после установки на ТВ

### ISSUE THREAD

**Issue by toperx** [vzakharchenko/rtsp-samsung-tv#7]
После установки приложения на тв оно запускается и показывает черный экран, с чем может быть связано?

**Comment by vzakharchenko** [comment]
Попробуй  посмотреть логи приложения
```
sudo pm2 logs server
```

**Comment by senbuvis** [comment]
У меня тоже самое, после установки CameraDevice на Samsung  UE65KS90502 при вызове показывает только черный экран.
Нет возможности ввести IP и порт сервера.
Сервер на raspberry работает нормально и конфигурируется.
В логах пусто.
Может быть можно как то получить http streams полученные в результате перекодировки rtsp, убедиться что сервер работает.

**Comment by vzakharchenko** [comment]
Что-бы посмотреть нормально ли работает перекодировка можно открыть страницу http://<SERVER>:3004/camera.html

Странно что в эмуляторе все хорошо работает.

**Comment by vzakharchenko** [comment]
Сделал возможное решение проблемы, это убравши обновление при загрузке приложения если не был введен IP и порт сервера.

Если не работает попробуйте ввести IP и порт прямо в код https://github.com/vzakharchenko/rtsp-samsung-tv/blob/ba8ef9fc0942b9676840bc3cb1290c7dd7d293f2/CameraDevice/main.js#L6:

```
  ip: localStorage.getItem('SERVER.IP') || '192.168.8.122', // <-- Server IP
  port: localStorage.getItem('SERVER.PORT') || '3004',
  inited: localStorage.getItem('SERVER.INITED') || true,
```

**Comment by senbuvis** [comment]
Привет Василий,
большое спасибо за ответ и за реализованное решение.
Я выяснил в чем была проблема.
Сервер на raspberry PI сразу заработал. Там проблем не было.
Мой телевизор 2016 г. и не поддерживает ЕS6 стандарт javascript.
Поэтому Camera Device аппликация не работала.
Посмотрел на debugger и обнаружил что везде где используются конструкции
типа: const, let, arrow functions и литералы ${var} выскакивают ошибки.
Переписал эти места и все начало работать.
Так что еще раз спасибо и я бы посоветовал выложить вариант без конструкций
ES6, думаю многие столкнуться с той же проблемой.
С уважением,
Дмитриюс.

**Comment by senbuvis** [comment]
Извините, еще забыл сказать что API
функция tizen.tvinputdevice.registerKeyBatch тоже не присутствует в
библиотеке.
Пришлось заменить ее на серию  tizen.tvinputdevice.registerKey
Может это баг в системе, а может она появилась позже.
У меня телевизор версии 2.4

**Comment by vzakharchenko** [comment]
@senbuvis  можете создать пулл реквест  с вашими изменниями, и я его посмотрю на телевизоре 2019 года

**Comment by senbuvis** [comment]
Может я проще перешлю вам все изменения,  вы уж там смотрите что вам
интересно.

**Comment by senbuvis** [comment]
Вот то что у меня работает

 CameraDevice.zip
<https://drive.google.com/file/d/17jwXvcaYtC4uKv-aw-HNWmF6z8pHg-li/view?usp=drive_web>
